The `Async{Fn, FnMut, FnOnce}` traits are not yet dyn-compatible.

Erroneous code example:

```compile_fail,E0802,edition2018
#![feature(async_closure)]
use core::ops::AsyncFn;

async fn call_async_fn_twice(some_fn: &dyn AsyncFn()) {
  some_fn().await;
  some_fn().await;
}
```

One workaround to this issue is to use `impl Async...` instead:

```edition2018
#![feature(async_closure)]
use core::ops::AsyncFn;

async fn call_async_fn_twice(some_fn: &impl AsyncFn()) {
  some_fn().await;
  some_fn().await;
}
```

This error indicates that you attempted to use `dyn AsyncFn`,
`dyn AsyncFnMut`, or `dyn AsyncFnOnce`.

This is not yet possible because the `Async...` traits internally return
a concrete `Future` associated type. For dynamic callsites, it is impossible
to know the size of the returned `Future` object since different
`Async...` implementations may return differently-sized `Future` objects.

This is analogous to the more general issue of creating a `dyn` type without
specifying associated types, e.g. `dyn Iterator` as opposed to
`dyn Iterator<Item = SomeItemType>`.
